name: Post Markdown Lint

on:
  push:
    paths:
      - '_posts/**.md'
  pull_request:
    paths:
      - '_posts/**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: '_posts/**/*.md'
